// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * This auton routine is for testing only. It should never be run during a match.
 */
public class AutonMinus1Test extends CommandGroup {
    
    public AutonMinus1Test() {
        addSequential(new DriveToAngle(45));
        addSequential(new Delay(1));
        addSequential(new DriveToAngle(-45));
        addSequential(new Delay(1));
        addSequential(new DriveToAngle(360));
    }
}
