// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 * This auton routine drives forward at top speed for two seconds.
 * Use this if shooter operation is broken.
 */
public class Auton1MobilityBonus extends CommandGroup {
    
    public  Auton1MobilityBonus() {
	addSequential(new ArcadeDriveWithInputs(-1,0,2));
    }
}
