// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import java.util.Random;

/**
 * This auton routine drives forward and scores a short shot in the goal.
 * It does NOT check if the goal is hot.
 */
public class Auton7GoalieAvoidance extends CommandGroup {
    
    public  Auton7GoalieAvoidance() {
        
        addSequential(new ArcadeDriveWithInputs(-1,0,1.65,true,true));
        
        addSequential(new ArcadeDriveWithInputs(-0.5,0,0.25,true,false));
        addSequential(new Delay(0.2));  // very brief stop for bot settling

        addSequential(new MoveArmOut());
        
        addSequential(new Delay(0.3));
        
        addSequential(new WaitForHotGoal());
//        addSequential(new Delay(1));
        
        Random rand = new Random();
        int sign = (rand.nextInt(2) == 1 ? 1 : -1);
        addSequential(new ArcadeDriveWithInputs(0,sign * 0.7,0.125,false,false));
        
        addSequential(new Shoot());

    }
}
