// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 * This auton routine does a long shot, then drives, gets the second ball,
 * and does a short shot. Obviously the name of this file does not currently
 * match up with the actual behavior of the routine.
 */
public class Auton4LongShort extends CommandGroup {
    
    public  Auton4LongShort() {
        addParallel(new TensionLauncher(),1.5); // This should stay tensioned
        addSequential(new MoveArmOut());
        
        addSequential(new Delay(0.5));
        
        addSequential(new Shoot(false));
        
        addParallel(new RunRollerBar(),0.5);
        addParallel(new UnwindWinch());
        addSequential(new ArcadeDriveWithInputs(0.75,0,0.5));
        
        addParallel(new MoveArmIn());
        addSequential(new ArcadeDriveWithInputs(-1,0,2.0));
        
        addSequential(new ArcadeDriveWithInputs(-0.5,0,0.5));
        
        addSequential(new MoveArmOut());
        
        addSequential(new Delay(0.5));
        
        addSequential(new Shoot());
    }
}
