// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 * This routine runs the automatic shoot sequence, which gets the shooter ready
 * to fire and then fires. It can optionally omit the last unwinding step so
 * that autonomous routines can proceed with other tasks and handle the
 * unsinding themselves.
 */
public class Shoot extends CommandGroup {
    
    /**
     * Constructs this command to go through the full sequence.
     */
    public Shoot() {
        this(true);
    }
    
    /**
     * Constructs this command to go through the sequence, with an option
     * to omit the final unwinding step.
     * @param unwind Whether to unwind the winch after the shot.
     */
    public Shoot(boolean unwind) {
        
	addSequential(new WinchLauncherDown());
	addSequential(new UnwindWinch());
	addSequential(new ReleaseLatch());
	addSequential(new WinchLauncherDown());
	if (unwind) {
            addSequential(new UnwindWinch());
            addSequential(new UnwindWinch(0.25,true));
        }
        
    }
}
