// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2175.Robot2014.Robot;

/**
 * This command unwinds the winch on the shooter. It will stop when the Sammy
 * Switch trips, unless the global override is pressed.
 */
public class  UnwindWinch extends Command {
    
    boolean timeoutOnly;
    
    public UnwindWinch() {
        this(1.5,false);
    }
    
    public UnwindWinch(double seconds, boolean onlyTimeout) {
        requires(Robot.launcher);
        timeoutOnly = onlyTimeout;
        setTimeout(seconds);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        System.out.println("Unwinding the winch...\n");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.launcher.RunWinchAtSpeed(-.6);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if (Robot.oi.shouldOverrideWinch()) {
            return false;
	} else if (timeoutOnly) {
            return isTimedOut();
        } else {
            return Robot.launcher.IsWinchUp() || isTimedOut();
	}
    }

    // Called once after isFinished returns true
    protected void end() {
        Robot.launcher.RunWinchAtSpeed(0);
	System.out.println("Done unwinding the winch.\n\n");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
